export const TIME_STAMPS_REQUEST = 'TIME_STAMPS_REQUEST';
export const TIME_STAMPS_SUCCESS = 'TIME_STAMPS_SUCCESS';
export const TIME_STAMPS_FAIL = 'TIME_STAMPS_FAIL';

export const TIME_STAMPS_EDIT_REQUEST = 'TIME_STAMPS_EDIT_REQUEST';
export const TIME_STAMPS_EDIT_SUCCESS = 'TIME_STAMPS_EDIT_SUCCESS';
export const TIME_STAMPS_EDIT_FAIL = 'TIME_STAMPS_EDIT_FAIL';