export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';

export const USER_SUBORDINATES_REQUEST = 'USER_SUBORDINATES_REQUEST';
export const USER_SUBORDINATES_SUCCESS = 'USER_SUBORDINATES_SUCCESS';
export const USER_SUBORDINATES_FAIL = 'USER_SUBORDINATES_FAIL';

export const USER_TIMESTAMPS_REQUEST = 'USER_TIMESTAMPS_REQUEST';
export const USER_TIMESTAMPS_SUCCESS = 'USER_TIMESTAMPS_SUCCESS';
export const USER_TIMESTAMPS_FAIL = 'USER_TIMESTAMPS_FAIL';

export const USER_TIMESTAMPS_EDIT_REQUEST = 'USER_TIMESTAMPS_EDIT_REQUEST';
export const USER_TIMESTAMPS_EDIT_SUCCESS = 'USER_TIMESTAMPS_EDIT_SUCCESS';
export const USER_TIMESTAMPS_EDIT_FAIL = 'USER_TIMESTAMPS_EDIT_FAIL';

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAIL = 'USER_EDIT_FAIL';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';

export const USER_REMOVE_REQUEST = 'USER_REMOVE_REQUEST';
export const USER_REMOVE_SUCCESS = 'USER_REMOVE_SUCCESS';
export const USER_REMOVE_FAIL = 'USER_REMOVE_FAIL';