// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Tms.DataLayer;
using Tms.DataLayer.Enums;

namespace Tms.DataLayer.Migrations
{
    [DbContext(typeof(TmsContext))]
    [Migration("20180507141203_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Tms.DataLayer.Entities.DbEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Blocked");

                    b.Property<Guid?>("DepartmentDirectorId");

                    b.Property<Guid?>("DirectorId");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("PassHash");

                    b.Property<int>("Role");

                    b.Property<string>("XrmId");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentDirectorId");

                    b.HasIndex("DirectorId");

                    b.ToTable("EmployeeEntities");
                });

            modelBuilder.Entity("Tms.DataLayer.Entities.DbTimeStamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("DbEmployeeId");

                    b.Property<TimeSpan>("WorkedTime");

                    b.HasKey("Id");

                    b.HasIndex("DbEmployeeId");

                    b.ToTable("TimeStampsEntities");
                });

            modelBuilder.Entity("Tms.DataLayer.Entities.DbEmployee", b =>
                {
                    b.HasOne("Tms.DataLayer.Entities.DbEmployee", "DepartmentDirector")
                        .WithMany()
                        .HasForeignKey("DepartmentDirectorId");

                    b.HasOne("Tms.DataLayer.Entities.DbEmployee", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId");
                });

            modelBuilder.Entity("Tms.DataLayer.Entities.DbTimeStamp", b =>
                {
                    b.HasOne("Tms.DataLayer.Entities.DbEmployee", "DbEmployee")
                        .WithMany("TimeStamps")
                        .HasForeignKey("DbEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
